let mot = "swim";
console.log(mot + "felicia");
console.log(mot);
let num = 20;
num = num * 2;
console.log(num);
let numberOfApple = 99;
let appleLeft = numberOfApple - 1;
console.log(appleLeft);
console.log(numberOfApple);